name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Debug: Kiểm tra thư mục hiện tại"
      run: pwd

    - name: "Debug: Danh sách file trong thư mục Twitter"
      run: ls -al ./Twitter

    - name: Create .env.staging file
      working-directory: ./Twitter
      run: echo "${{ secrets.TWITTER_ENV_PRODUCTION }}" > .env.staging

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      working-directory: ./Twitter
      run: docker build . --file Dockerfile.dev --tag doanvovantrong/twitter:v4

    - name: Push Docker Image
      run: docker push doanvovantrong/twitter:v4
